# Change these first
owner: scaler-ai # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Companion Frontend
    url: https://companion.scaler.com
  - name: Companion Backend
    url: https://api.companion.scaler.com/api/docs
    headers:
      - "Authorization: Basic ${{ secrets.BACKEND_AUTH }}"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://ibpublicimages.s3.us-west-2.amazonaws.com/vector/companion/chatbot_logo.svg
  name: Companion
  introTitle: "Companion Uptime Monitor"
  introMessage: This is a companion uptime monitor for the [**Companion**](https://companion.scaler.com) project .
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

